package iac

import (
	"fmt"
	"strings"
	"time"
)

// TerraformGenerator generates Terraform scripts for AWS optimizations
type TerraformGenerator struct {
	provider string
	region   string
}

// NewTerraformGenerator creates a new Terraform generator
func NewTerraformGenerator(provider, region string) *TerraformGenerator {
	return &TerraformGenerator{
		provider: provider,
		region:   region,
	}
}

// GenerateEC2Optimization generates Terraform for EC2 instance optimization
func (tg *TerraformGenerator) GenerateEC2Optimization(recommendation *OptimizationRecommendation) *IaCScript {
	var terraformCode strings.Builder
	
	// Provider configuration
	terraformCode.WriteString(fmt.Sprintf(`# Generated by Yukti FinOps - %s
# Recommendation: %s
# Estimated Savings: $%.2f

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "%s"
}

`, time.Now().Format("2006-01-02 15:04:05"), recommendation.Action, recommendation.EstimatedSavings, tg.region))

	switch recommendation.Action {
	case "downsize":
		terraformCode.WriteString(tg.generateDownsizeScript(recommendation))
	case "terminate":
		terraformCode.WriteString(tg.generateTerminateScript(recommendation))
	case "schedule":
		terraformCode.WriteString(tg.generateScheduleScript(recommendation))
	case "spot_conversion":
		terraformCode.WriteString(tg.generateSpotConversionScript(recommendation))
	}

	// Add rollback script
	rollbackCode := tg.generateRollbackScript(recommendation)

	return &IaCScript{
		ID:               fmt.Sprintf("tf-%s-%d", recommendation.ResourceID, time.Now().Unix()),
		Type:             "terraform",
		Provider:         "aws",
		Action:           recommendation.Action,
		ResourceID:       recommendation.ResourceID,
		Code:             terraformCode.String(),
		RollbackCode:     rollbackCode,
		EstimatedSavings: recommendation.EstimatedSavings,
		GeneratedAt:      time.Now(),
		Instructions:     tg.generateInstructions(recommendation),
	}
}

// generateDownsizeScript generates Terraform for instance downsizing
func (tg *TerraformGenerator) generateDownsizeScript(rec *OptimizationRecommendation) string {
	return fmt.Sprintf(`# Downsize EC2 instance for cost optimization
data "aws_instance" "target" {
  instance_id = "%s"
}

# Stop instance before resizing
resource "aws_ec2_instance_state" "stop_instance" {
  instance_id = data.aws_instance.target.id
  state       = "stopped"
}

# Modify instance type
resource "aws_instance" "optimized" {
  ami           = data.aws_instance.target.ami
  instance_type = "%s"  # Recommended smaller instance type
  
  # Preserve existing configuration
  key_name               = data.aws_instance.target.key_name
  vpc_security_group_ids = data.aws_instance.target.vpc_security_group_ids
  subnet_id              = data.aws_instance.target.subnet_id
  
  # Preserve tags
  tags = data.aws_instance.target.tags
  
  # Replace the existing instance
  replace_triggered_by = [aws_ec2_instance_state.stop_instance]
}

output "old_instance_type" {
  value = data.aws_instance.target.instance_type
}

output "new_instance_type" {
  value = aws_instance.optimized.instance_type
}

output "estimated_monthly_savings" {
  value = "%.2f USD"
}
`, rec.ResourceID, rec.RecommendedInstanceType, rec.EstimatedSavings*30)
}

// generateTerminateScript generates Terraform for instance termination
func (tg *TerraformGenerator) generateTerminateScript(rec *OptimizationRecommendation) string {
	return fmt.Sprintf(`# Terminate unused EC2 instance
data "aws_instance" "target" {
  instance_id = "%s"
}

# Create AMI backup before termination
resource "aws_ami_from_instance" "backup" {
  name               = "backup-${data.aws_instance.target.id}-${formatdate("YYYY-MM-DD", timestamp())}"
  source_instance_id = data.aws_instance.target.id
  
  tags = merge(data.aws_instance.target.tags, {
    Purpose = "Pre-termination backup"
    CreatedBy = "Yukti-FinOps"
  })
}

# Terminate instance (commented out for safety)
# Uncomment the following resource after reviewing
/*
resource "aws_instance" "terminate" {
  instance_id = data.aws_instance.target.id
  
  # This will terminate the instance
  lifecycle {
    prevent_destroy = false
  }
}
*/

output "backup_ami_id" {
  value = aws_ami_from_instance.backup.id
}

output "estimated_monthly_savings" {
  value = "%.2f USD"
}
`, rec.ResourceID, rec.EstimatedSavings*30)
}

// generateScheduleScript generates Terraform for instance scheduling
func (tg *TerraformGenerator) generateScheduleScript(rec *OptimizationRecommendation) string {
	return fmt.Sprintf(`# Schedule EC2 instance for cost optimization
data "aws_instance" "target" {
  instance_id = "%s"
}

# Lambda function for instance scheduling
resource "aws_lambda_function" "scheduler" {
  filename         = "scheduler.zip"
  function_name    = "ec2-scheduler-${data.aws_instance.target.id}"
  role            = aws_iam_role.scheduler_role.arn
  handler         = "index.handler"
  runtime         = "python3.9"
  
  environment {
    variables = {
      INSTANCE_ID = data.aws_instance.target.id
    }
  }
}

# IAM role for Lambda
resource "aws_iam_role" "scheduler_role" {
  name = "ec2-scheduler-role-${data.aws_instance.target.id}"
  
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# CloudWatch Events for scheduling
resource "aws_cloudwatch_event_rule" "stop_schedule" {
  name                = "stop-${data.aws_instance.target.id}"
  description         = "Stop instance at 6 PM"
  schedule_expression = "cron(0 18 * * ? *)"  # 6 PM daily
}

resource "aws_cloudwatch_event_rule" "start_schedule" {
  name                = "start-${data.aws_instance.target.id}"
  description         = "Start instance at 8 AM"
  schedule_expression = "cron(0 8 * * ? *)"   # 8 AM daily
}

output "estimated_monthly_savings" {
  value = "%.2f USD (58%% uptime reduction)"
}
`, rec.ResourceID, rec.EstimatedSavings*30)
}

// generateSpotConversionScript generates Terraform for Spot instance conversion
func (tg *TerraformGenerator) generateSpotConversionScript(rec *OptimizationRecommendation) string {
	return fmt.Sprintf(`# Convert to Spot instance for cost optimization
data "aws_instance" "target" {
  instance_id = "%s"
}

# Launch template for Spot instance
resource "aws_launch_template" "spot_template" {
  name_prefix   = "spot-${data.aws_instance.target.id}-"
  image_id      = data.aws_instance.target.ami
  instance_type = data.aws_instance.target.instance_type
  
  vpc_security_group_ids = data.aws_instance.target.vpc_security_group_ids
  key_name              = data.aws_instance.target.key_name
  
  instance_market_options {
    market_type = "spot"
    spot_options {
      max_price = "%.4f"  # 70%% of on-demand price
    }
  }
  
  tag_specifications {
    resource_type = "instance"
    tags = merge(data.aws_instance.target.tags, {
      SpotInstance = "true"
      ConvertedBy = "Yukti-FinOps"
    })
  }
}

# Auto Scaling Group for Spot instance
resource "aws_autoscaling_group" "spot_asg" {
  name                = "spot-asg-${data.aws_instance.target.id}"
  vpc_zone_identifier = [data.aws_instance.target.subnet_id]
  min_size            = 1
  max_size            = 1
  desired_capacity    = 1
  
  launch_template {
    id      = aws_launch_template.spot_template.id
    version = "$Latest"
  }
}

output "estimated_monthly_savings" {
  value = "%.2f USD (70%% cost reduction)"
}
`, rec.ResourceID, rec.EstimatedSavings*0.7, rec.EstimatedSavings*30)
}

// generateRollbackScript generates rollback Terraform script
func (tg *TerraformGenerator) generateRollbackScript(rec *OptimizationRecommendation) string {
	return fmt.Sprintf(`# ROLLBACK SCRIPT - Use if optimization needs to be reverted
# Generated for: %s

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "%s"
}

# Rollback to original configuration
# This script restores the resource to its previous state
# Review and modify as needed before applying

# NOTE: Specific rollback steps depend on the optimization applied
# Consult the original resource configuration before proceeding
`, rec.ResourceID, tg.region)
}

// generateInstructions generates step-by-step instructions
func (tg *TerraformGenerator) generateInstructions(rec *OptimizationRecommendation) []string {
	return []string{
		"1. Review the generated Terraform code carefully",
		"2. Ensure you have appropriate AWS credentials configured",
		"3. Run 'terraform init' to initialize the configuration",
		"4. Run 'terraform plan' to review the changes",
		"5. If satisfied, run 'terraform apply' to implement the optimization",
		"6. Monitor the resource after changes are applied",
		"7. Keep the rollback script for emergency restoration",
		fmt.Sprintf("8. Expected savings: $%.2f per month", rec.EstimatedSavings*30),
	}
}

// OptimizationRecommendation represents a cost optimization recommendation
type OptimizationRecommendation struct {
	ResourceID              string  `json:"resource_id"`
	Action                  string  `json:"action"`
	RecommendedInstanceType string  `json:"recommended_instance_type"`
	EstimatedSavings        float64 `json:"estimated_savings"`
	Confidence              float64 `json:"confidence"`
	Reasoning               string  `json:"reasoning"`
}

// IaCScript represents a generated Infrastructure-as-Code script
type IaCScript struct {
	ID               string    `json:"id"`
	Type             string    `json:"type"`
	Provider         string    `json:"provider"`
	Action           string    `json:"action"`
	ResourceID       string    `json:"resource_id"`
	Code             string    `json:"code"`
	RollbackCode     string    `json:"rollback_code"`
	EstimatedSavings float64   `json:"estimated_savings"`
	GeneratedAt      time.Time `json:"generated_at"`
	Instructions     []string  `json:"instructions"`
}