package remediation

import (
	"fmt"
	"strings"
	"time"
)

type TerraformGenerator struct {
	customerID string
}

type RemediationAction struct {
	Type        string            `json:"type"`
	ResourceID  string            `json:"resource_id"`
	Action      string            `json:"action"`
	Parameters  map[string]string `json:"parameters"`
	EstSavings  float64           `json:"estimated_savings"`
	Risk        string            `json:"risk"`
}

func NewTerraformGenerator(customerID string) *TerraformGenerator {
	return &TerraformGenerator{customerID: customerID}
}

func (t *TerraformGenerator) GenerateInstanceRightSizing(instanceID, currentType, recommendedType string, monthlySavings float64) string {
	template := `# Generated by Yukti FinOps - Instance Right-sizing
# Customer: %s
# Generated: %s
# Estimated Monthly Savings: $%.2f

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Right-size EC2 instance from %s to %s
resource "aws_instance" "optimized_%s" {
  # Current instance: %s
  instance_type = "%s"
  
  # Copy configuration from existing instance
  ami                    = data.aws_instance.current.ami
  key_name              = data.aws_instance.current.key_name
  vpc_security_group_ids = data.aws_instance.current.vpc_security_group_ids
  subnet_id             = data.aws_instance.current.subnet_id
  
  # Preserve tags
  tags = merge(
    data.aws_instance.current.tags,
    {
      "OptimizedBy" = "Yukti-FinOps"
      "OriginalType" = "%s"
      "OptimizedDate" = "%s"
    }
  )
  
  lifecycle {
    create_before_destroy = true
  }
}

# Data source for current instance
data "aws_instance" "current" {
  instance_id = "%s"
}

# Output the new instance details
output "optimized_instance_id" {
  value = aws_instance.optimized_%s.id
}

output "estimated_monthly_savings" {
  value = "%.2f"
}

# IMPORTANT: Review this configuration before applying
# 1. Verify the instance type change is appropriate
# 2. Test in non-production environment first
# 3. Schedule maintenance window for production changes
# 4. Backup any critical data before proceeding
`

	return fmt.Sprintf(template,
		t.customerID,
		time.Now().Format("2006-01-02 15:04:05"),
		monthlySavings,
		currentType, recommendedType,
		strings.ReplaceAll(instanceID, "-", "_"),
		instanceID,
		recommendedType,
		currentType,
		time.Now().Format("2006-01-02"),
		instanceID,
		strings.ReplaceAll(instanceID, "-", "_"),
		monthlySavings,
	)
}

func (t *TerraformGenerator) GenerateInstanceTermination(instanceID string, reason string, monthlySavings float64) string {
	template := `# Generated by Yukti FinOps - Instance Termination
# Customer: %s
# Generated: %s
# Reason: %s
# Estimated Monthly Savings: $%.2f

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Terminate unused EC2 instance
# WARNING: This will permanently delete the instance
resource "null_resource" "terminate_%s" {
  provisioner "local-exec" {
    command = "aws ec2 terminate-instances --instance-ids %s"
  }
  
  # Add confirmation step
  provisioner "local-exec" {
    command = "echo 'Instance %s terminated - Estimated savings: $%.2f/month'"
  }
}

# Data source for instance details (for reference)
data "aws_instance" "target" {
  instance_id = "%s"
}

output "terminated_instance" {
  value = {
    instance_id = "%s"
    instance_type = data.aws_instance.target.instance_type
    reason = "%s"
    estimated_savings = "%.2f"
  }
}

# CRITICAL WARNINGS:
# 1. This will PERMANENTLY DELETE the instance
# 2. Ensure all data is backed up
# 3. Verify no applications depend on this instance
# 4. Consider stopping instead of terminating for testing
# 5. Review with your team before applying
`

	return fmt.Sprintf(template,
		t.customerID,
		time.Now().Format("2006-01-02 15:04:05"),
		reason,
		monthlySavings,
		strings.ReplaceAll(instanceID, "-", "_"),
		instanceID,
		instanceID,
		monthlySavings,
		instanceID,
		instanceID,
		reason,
		monthlySavings,
	)
}

func (t *TerraformGenerator) GenerateReservedInstancePlan(instanceType, region string, quantity int, monthlySavings float64) string {
	template := `# Generated by Yukti FinOps - Reserved Instance Purchase
# Customer: %s
# Generated: %s
# Estimated Monthly Savings: $%.2f

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Reserved Instance purchase recommendation
# This is a planning template - actual RI purchases are done through AWS Console
resource "null_resource" "reserved_instance_plan" {
  provisioner "local-exec" {
    command = <<-EOT
      echo "Reserved Instance Recommendation:"
      echo "Instance Type: %s"
      echo "Region: %s"
      echo "Quantity: %d"
      echo "Term: 1 year"
      echo "Payment: No Upfront"
      echo "Estimated Monthly Savings: $%.2f"
      echo ""
      echo "To purchase, visit AWS Console > EC2 > Reserved Instances"
    EOT
  }
}

output "reserved_instance_recommendation" {
  value = {
    instance_type = "%s"
    region = "%s"
    quantity = %d
    term = "1year"
    payment_option = "NoUpfront"
    estimated_monthly_savings = "%.2f"
    purchase_url = "https://console.aws.amazon.com/ec2/v2/home?region=%s#ReservedInstances:"
  }
}

# NOTE: Reserved Instances cannot be managed directly through Terraform
# This template provides the recommendation and purchase guidance
`

	return fmt.Sprintf(template,
		t.customerID,
		time.Now().Format("2006-01-02 15:04:05"),
		monthlySavings,
		instanceType,
		region,
		quantity,
		monthlySavings,
		instanceType,
		region,
		quantity,
		monthlySavings,
		region,
	)
}

func (t *TerraformGenerator) GenerateCloudFormationTemplate(action RemediationAction) string {
	switch action.Type {
	case "rightsizing":
		return t.generateCFRightSizing(action)
	case "termination":
		return t.generateCFTermination(action)
	default:
		return "# Unsupported action type for CloudFormation"
	}
}

func (t *TerraformGenerator) generateCFRightSizing(action RemediationAction) string {
	template := `AWSTemplateFormatVersion: '2010-09-09'
Description: 'Yukti FinOps - EC2 Instance Right-sizing'

Parameters:
  InstanceId:
    Type: String
    Default: '%s'
    Description: 'Instance ID to optimize'
  
  NewInstanceType:
    Type: String
    Default: '%s'
    Description: 'Recommended instance type'

Resources:
  OptimizedInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref NewInstanceType
      ImageId: !GetAtt CurrentInstance.ImageId
      KeyName: !GetAtt CurrentInstance.KeyName
      SecurityGroupIds: !GetAtt CurrentInstance.SecurityGroupIds
      SubnetId: !GetAtt CurrentInstance.SubnetId
      Tags:
        - Key: OptimizedBy
          Value: Yukti-FinOps
        - Key: OriginalType
          Value: !GetAtt CurrentInstance.InstanceType
        - Key: EstimatedSavings
          Value: '%.2f'

Outputs:
  NewInstanceId:
    Description: 'Optimized instance ID'
    Value: !Ref OptimizedInstance
  
  EstimatedMonthlySavings:
    Description: 'Estimated monthly savings'
    Value: '%.2f'
`

	return fmt.Sprintf(template,
		action.ResourceID,
		action.Parameters["recommended_type"],
		action.EstSavings,
		action.EstSavings,
	)
}

func (t *TerraformGenerator) generateCFTermination(action RemediationAction) string {
	template := `AWSTemplateFormatVersion: '2010-09-09'
Description: 'Yukti FinOps - EC2 Instance Termination'

Parameters:
  InstanceId:
    Type: String
    Default: '%s'
    Description: 'Instance ID to terminate'

Resources:
  TerminationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'yukti-terminate-${InstanceId}'
      Runtime: python3.9
      Handler: index.handler
      Code:
        ZipFile: |
          import boto3
          import json
          
          def handler(event, context):
              ec2 = boto3.client('ec2')
              instance_id = event['InstanceId']
              
              try:
                  response = ec2.terminate_instances(InstanceIds=[instance_id])
                  return {
                      'statusCode': 200,
                      'body': json.dumps(f'Instance {instance_id} terminated successfully')
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'body': json.dumps(f'Error: {str(e)}')
                  }
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EC2TerminatePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:TerminateInstances
                Resource: '*'

Outputs:
  LambdaFunctionArn:
    Description: 'Lambda function for termination'
    Value: !GetAtt TerminationLambda.Arn
  
  EstimatedMonthlySavings:
    Description: 'Estimated monthly savings'
    Value: '%.2f'
`

	return fmt.Sprintf(template, action.ResourceID, action.EstSavings)
}