import React, { useState } from 'react';
import { Code, Download, CheckCircle } from 'lucide-react';
import api from '../../../services/api';
import { Button } from '../../ui/button';
import { Select } from '../../ui/select';
import { Alert } from '../../ui/alert';

interface IaCGeneratorTabProps {
  resourceId: string;
  resourceType: string;
}

const IaCGeneratorTab: React.FC<IaCGeneratorTabProps> = ({
  resourceId,
  resourceType,
}) => {
  const [format, setFormat] = useState<'terraform' | 'cloudformation'>('terraform');
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    try {
      setError(null);
      setLoading(true);
      const tenantId = localStorage.getItem('tenant_id') || 'tenant-001';
      
      const data = await api.post('/api/v1/iac/generate', {
        resource_id: resourceId,
        resource_type: resourceType,
        format: format.toLowerCase(),
        tenant_id: tenantId
      });
      
      if (data.code) {
        setGeneratedCode(data.code);
      } else {
        setError('No code was generated by the server');
      }
    } catch (error) {
      console.error('Error generating IaC:', error);
      setError(error instanceof Error ? error.message : 'Failed to generate code');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${resourceId}-${format.toLowerCase()}.tf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Select
            value={format}
            onValueChange={(value: 'terraform' | 'cloudformation') => setFormat(value)}
          >
            <option value="terraform">Terraform</option>
            <option value="cloudformation">CloudFormation</option>
          </Select>
          <Button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2"
          >
            <Code className="h-4 w-4" />
            {loading ? 'Generating...' : 'Generate IaC'}
          </Button>
        </div>
        {generatedCode && (
          <Button onClick={handleDownload} variant="outline">
            <Download className="h-4 w-4 mr-2" />
            Download
          </Button>
        )}
      </div>

      {error && (
        <Alert variant="destructive">
          {error}
        </Alert>
      )}

      {generatedCode && (
        <div className="relative">
          <pre className="p-4 bg-gray-50 rounded-lg overflow-auto max-h-[500px]">
            <code>{generatedCode}</code>
          </pre>
          <div className="absolute top-2 right-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                navigator.clipboard.writeText(generatedCode);
              }}
            >
              <CheckCircle className="h-4 w-4 mr-2" />
              Copy
            </Button>
          </div>
        </div>
      )}
    </div>
  );
};

export default IaCGeneratorTab;